# Generated by Django 5.1.4 on 2024-12-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(default=0)),
                ('q2', models.IntegerField(default=0)),
                ('q3', models.IntegerField(default=0)),
                ('q4', models.IntegerField(default=0)),
                ('q5', models.IntegerField(default=0)),
                ('q6', models.IntegerField(default=0)),
                ('q7', models.IntegerField(default=0)),
                ('q8', models.IntegerField(default=0)),
                ('q9', models.IntegerField(default=0)),
                ('q10', models.IntegerField(default=0)),
                ('q11', models.IntegerField(default=0)),
                ('q12', models.IntegerField(default=0)),
                ('q13', models.IntegerField(default=0)),
                ('q14', models.IntegerField(default=0)),
                ('q15', models.IntegerField(default=0)),
                ('q16', models.IntegerField(default=0)),
                ('q17', models.IntegerField(default=0)),
                ('q18', models.IntegerField(default=0)),
                ('q19', models.IntegerField(default=0)),
                ('q20', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
