# Generated by Django 5.1.4 on 2025-01-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.IntegerField()),
                ('question2', models.IntegerField()),
                ('question3', models.IntegerField()),
                ('question4', models.IntegerField()),
                ('question5', models.IntegerField()),
                ('question6', models.IntegerField()),
                ('question7', models.IntegerField()),
                ('question8', models.IntegerField()),
                ('question9', models.IntegerField()),
                ('question10', models.IntegerField()),
                ('question11', models.IntegerField()),
                ('question12', models.IntegerField()),
                ('question13', models.IntegerField()),
                ('question14', models.IntegerField()),
                ('question15', models.IntegerField()),
                ('question16', models.IntegerField()),
                ('question17', models.IntegerField()),
                ('question18', models.IntegerField()),
                ('question19', models.IntegerField()),
                ('question20', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
