# Generated by Django 5.1.4 on 2025-01-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_diagnosisresult_delete_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question10',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question1',
            new_name='q10',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question11',
            new_name='q11',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question12',
            new_name='q12',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question13',
            new_name='q13',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question14',
            new_name='q14',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question15',
            new_name='q15',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question16',
            new_name='q16',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question17',
            new_name='q17',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question18',
            new_name='q18',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question19',
            new_name='q19',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question2',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question20',
            new_name='q20',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question3',
            new_name='q3',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question4',
            new_name='q4',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question5',
            new_name='q5',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question6',
            new_name='q6',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question7',
            new_name='q7',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question8',
            new_name='q8',
        ),
        migrations.RenameField(
            model_name='diagnosisresult',
            old_name='question9',
            new_name='q9',
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='result_type',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
